// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydgealwfrvnpjkzzozgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZ2VhbHdmcnZucGprenpvemdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzc1OTMsImV4cCI6MjA2NDk1MzU5M30.98cJcyXm2ICadmZ2uun6vmpfLOEXEwfjTrn6ooe17Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);